'\" t
.\"     Title: cbbackupmgr-collect-logs
.\"    Author: Couchbase
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2019-07-22
.\"    Manual: Backup Manual
.\"    Source: Backup 1.0.0
.\"  Language: English
.\"
.TH "CBBACKUPMGR\-COLLECT\-LOGS" "1" "2019-07-22" "Backup 1.0.0" "Backup Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
cbbackupmgr\-collect\-logs \- Collects debugging information from a backup archive
.SH "SYNOPSIS"
.sp
.sp
.nf
cbbackupmgr collect\-logs [\-\-archive <archive_dir>] [\-\-output\-dir <dir>]
                         [\-\-redact] [\-\-salt <salt>]
.fi
.br
.SH "DESCRIPTION"
.sp
Collects debugging information to make it easier to debug user issues. This
command collects the logs, the output of the list command, the range.json files
from each backup, the seqnos and failover logs from each backup, and the
backup_meta.json files from each repo. This data is put into a zip file that
contains the date that the collect\-info command was run. This command will only
collect meta from the backup archive.
.SH "OPTIONS"
.sp
Below are a list of parameters for the compact command.
.SS "Required"
.sp
\-a,\-\-archive <archive_dir>
.RS 4
The location of the archive directory.
.RE
.sp
\-o,\-\-output_dir <dir>
.RS 4
Specifies a path where the zip file that this command writes should be
written. If this flag is not used then the zip file is written to the logs
directory of the archive the command is run against.
.RE
.SS "Optional"
.sp
\-\-redact
.RS 4
When the redact flag is specified a redacted copy of the logs will be
produced, in the same directory as the un\-redacted version. The redacted
zip directory will be prefixed by `redacted\-`.
.RE
.sp
\-\-salt <salt>
.RS 4
Specifies the salt to used to hash the data. If possible the salt should be
the same used by Couchbase Server to allow the logs to be easily cross
referenced. The Couchbase Server salt is at the top of the couchbase.log in
the zip file generated by cbcollect_info. If no salt is specified it will be
auto\-generated.
.RE
.SH "EXAMPLES"
.sp
To generate debugging information for an archive dir "/data/backup" and output
the file to "/data/output/logs" run the following command.
.sp
.if n .RS 4
.nf
$ cbbackupmgr collect\-logs \-a /data/backup
.fi
.if n .RE
.sp
To generate debugging information for an archive dir "/data/backup" and output
the file to "/tmp" run the following command.
.sp
.if n .RS 4
.nf
$ cbbackupmgr collect\-logs \-a /data/backup \-o /tmp
.fi
.if n .RE
.SH "ENVIRONMENT AND CONFIGURATION VARIABLES"
.sp
CB_ARCHIVE_PATH
.RS 4
Specifies the path to the backup archive. If the archive path is supplied as
a command line argument then this value is overridden.
.RE
.SH "SEE ALSO"
.sp
\fBcbbackupmgr\-list\fP(1),
.SH "CBBACKUPMGR"
.sp
Part of the \fBcbbackupmgr\fP(1) suite
.SH "AUTHOR"
.sp
Couchbase